version: '2'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=mystique
      - MYSQL_PASSWORD=mystique
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=mydb
